### ISSUE TITLE
SVG selectors & other attributes highlighten

### ISSUE THREAD

**Issue by joSFD** [SublimeText/Sass#111]
Hello there, 

I would like to report this... Not sure it is intentional.  This doesn't seem right to my eyes...

![header scss — ALL 2024-10-11 at 1 39 21 PM](https://github.com/user-attachments/assets/3e9db567-30d1-4bce-a8d0-4c8ff7a17558)

Best,
Johan

**Comment by deathaxe** [comment]
What Sublime Text version are you using?

It seems to work fine on ST4180.

![grafik](https://github.com/user-attachments/assets/98794770-523c-4b90-b017-f6815f68b4e3)

```SCSS
button[type="submit"] {

    .icon {
        svg {
            width: 100%;
            height: 100%;
            path {
                fill:#000;
            }
        }
    }
}

button[type="submit"] {

    .icon {
        svg {
            width: 100%;
            * {
                stroke: $touch2;
            }
        }
    }
}
```
