### ISSUE TITLE
Trying to insert inline comment creates outer block comment

### ISSUE THREAD

**Issue by rchl** [SublimeText/Sass#95]
Trying to insert inline comment at `|` with `cmd`+`/` comments out the parent selector with a block comment.

```scss
#a {
    |
    #b {
        display: none;
    }
}
```

=>

```scss
/* #a {
    
    #b {
        display: none;
    }
} */
```

I wonder if it's possible to fix without loosing the functionality to easily comment out whole selectors as it's quite useful.
